export { default as backArrow } from './backArrow.svg';
export { default as nextArrow } from './nextArrow.svg';
export { default as getStartedStar } from './getStartedStar.svg';
export { default as onboardingLogo } from './onboardingLogo.svg';
export { default as eyeOpen } from "./eyeOpen.svg";
export { default as eyeClose } from "./eyeClose.svg";
export { default as cross } from "./cross.svg";
export { default as errorInput } from "./errorInput.svg";
export { default as mail } from "./mail.svg";
export { default as noConnection } from "./noConnection.svg"
export { default as refresh } from "./refresh.svg"
export { default as toastSuccess } from "./toastSuccess.svg"
export { default as toastError } from "./toastError.svg"
export { default as closeButton } from "./closeButton.svg"
export { default as calendar } from "./calendar.svg"
export { default as calendarIcon } from "./calendarIcon.svg"
export { default as newMeeting } from "./newMeeting.svg"
export { default as settings } from "./settings.svg"
export { default as leftButton } from "./leftButton.svg"
export { default as rightButton } from "./rightButton.svg"
export { default as meetingLogo } from "./meetingLogo.svg"
export { default as videoIcon } from "./videoIcon.svg"
export { default as scheduleMeeting } from "./scheduleMeeting.svg"
export { default as check } from "./check.svg"
export { default as downArrow } from "./downArrow.svg"
export { default as copy } from "./copy.svg"
export { default as clock } from "./clock.svg"
export { default as participants } from "./participants.svg"
export { default as info } from "./info.svg"
export { default as successCheck } from "./successCheck.svg"
export { default as errorCheck } from "./errorCheck.svg"
export { default as avatarEmpty } from "./avatarEmpty.svg"