export enum ScreensEnum {
  ONBOARDING = "Onboarding",
  LOGIN = "LOGIN",
  SIGN_UP = "SIGN_UP",
  VERIFICATION = "VERIFICATION",
  RESET_PASSWORD = "RESET_PASSWORD",
  CREATE_PASSWORD = "CREATE_PASSWORD",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  NO_CONNECTION = "NO_CONNECTION",
  SETUP_PROFILE = "SETUP_PROFILE",
  MEETING_DETAILS = "MEETING_DETAILS",
  MEETING = "MEETING",
  // Bottom tab routes
  MAIN = "MAIN",
  CALENDAR = "Calendar",
  NEW_MEETING = "New Meeting",
  SETTINGS = "Settings",
}
